---
- hosts: all
  gather_facts: yes
  tasks:
   - name: Dump all variables
     action: template src=dumpall.j2 dest=/tmp/ansible_dump.all

- hosts:  awx-turnkey-k8s
  gather_facts: yes
  roles:
   - role: awx-turnkey-venv-installer
