- name: distribute reqfile
  ansible.builtin.copy:
    src:  awxrpm.requirements.txt
    dest: /tmp/awxrpm.requirements.txt
    force: yes
    mode: '0600'

- name: create download_pip
  ansible.builtin.copy:
    src:  download_pip.py
    dest: /tmp/download.pip.py
    force: yes
    mode: '0755'

- name:  create build venv
  ansible.builtin.pip:
    requirements: /tmp/awxrpm.requirements.txt
    virtualenv: /var/awx/buildvenv
    virtualenv_command: /usr/bin/python3 -m venv
  become: True

- name: create symlinks
  shell: ln -fsv /usr/include/python3.8/* /usr/include/
  become: True

- name: upgrade pip in build env
  shell: /var/awx/buildvenv/bin/pip install  --upgrade pip
  become: True

- name: download sources
  shell: /var/awx/buildvenv/bin/python /tmp/download.pip.py
  become: True
