- name: distribute reqfile
  ansible.builtin.copy:
    src:  awxrpm.requirements.txt
    dest: /tmp/awxrpm.requirements.txt
    force: yes
    mode: '0600'

- name: create download_pip
  ansible.builtin.copy:
    src:  download_pip.py
    dest: /tmp/download.pip.py
    force: yes
    mode: '0755'

- name:  create venv
  ansible.builtin.pip:
    name: requirements-parser
    virtualenv: /var/awx/venv
    virtualenv_command: /usr/bin/python3 -m venv
  become: True

- name: create symlinks
  shell: ln -sv /usr/include/python3.6m/* /usr/include/
  become_user: awx
  become: True
