- name: Enable EPEL Repository on CentOS 8
  dnf:
    name: epel-release
    state: latest
  become: True
  when: ansible_facts['os_family'] == 'RedHat'

- name: depend | Ensure dependencies are installed.
  dnf:
    pkg: [
                'jq',
                'git',
                'python3-virtualenv',
                'gcc-c++',
                'lvm2',
                'bzip2',
                'python3-pip',
                'ansible',
                'gcc',
                'openldap-devel',
                'xmlsec1-openssl',
                '@Development Tools',
                'python3.8',
                'python3.8-devel',
                'python38-cryptography',
                'rpm-build',
                'rpm-build-libs',
                'python3-requests', 
                'libffi-devel',
                'gcc',
                'postgresql-devel'
        ]
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install add  packages
  yum:
    name:
      - xmlsec1-devel
      - libtool-ltdl-devel
      - mlocate
      - libpq-devel
    state: latest
    enablerepo: "powertools"
  become: True
  when: ansible_facts['os_family'] == 'RedHat'

- name: Add the group 'awx' with a specific gid and
  ansible.builtin.group:
    name: awx
    state: present
    gid: 1666
  become: True

- name: Git checkout awx
  ansible.builtin.git:
    repo: 'https://github.com/ansible/awx.git'
    dest: /tmp/awx
    version: "{{ awx_image_version }}"
    force: True
  become: True
  become_user: awx

- name: Create scl dir
  file:
    path: /var/awxrpm/scl
    owner: root
    group: root
    state: directory
    mode: "u=rwx,g=rwx,o=r"
  become: yes 

- name: create define_scl_dependcy.sh
  template:
    src: define_scl_dependcy.sh.j2
    dest: /usr/local/bin/define_scl_dependcy.sh
    force: yes
    mode: '0770'
    owner: root
    group: root
  become: True


- name: create build_awx_sdist.sh.j2 
  template:
    src: build_awx_sdist.sh.j2
    dest: /usr/local/bin/build_awx_sdist.sh
    force: yes
    mode: '0770'
    owner: root
    group: root
  become: True

- name: create master awxrpm.scl.spec
  template:
    src: awxrpm.scl.spec.j2
    dest: /var/awxrpm/scl/awxrpm.scl.spec
    force: yes
    mode: '0660'
    owner: root
    group: root
  become: True