- name: install awx-from-source 
  action: template src=dumpall.j2 dest=/tmp/ansible_dump.all

- name: run awx setup install
  ansible.builtin.command: /var/awx/venv/bin/python setup.py install
  become: yes
  args:
    chdir:  /tmp/awx

- name: django-debug-toolbar 
  ansible.builtin.command: /var/awx/venv/bin/pip install django-debug-toolbar
  become: yes
  args:
    chdir:  /tmp/awx

- name: django-rest-swagger
  ansible.builtin.command: /var/awx/venv/bin/pip install django-rest-swagger
  become: yes
  args:
    chdir:  /tmp/awx

- name: Creates tower
  file:
    path: /etc/tower/conf.d
    state: directory
    owner: awx
    group: awx
    mode: 0770
    recurse: yes
  become: True

- name: Ensure awx is in the nginx group
  user:
    append: yes
    name: awx
    groups: nginx
  become: True

- name: Configure the Tower socket directory.
  file: path=/var/run/tower state=directory owner=nginx group=nginx mode=2775
  become: True

- name: Configure the Tower socket directory for tmpfiles.d
  template:
    src: tower.conf.j2
    dest: /etc/tmpfiles.d/tower.conf
    force: yes
    mode: '0640'
    owner: root
    group: root
  become: True

- name: Configure the awx settings file
  template:
    src: settings.py.j2
    dest: /etc/tower/settings.py
    force: yes
    mode: '0640'
    owner: awx
    group: awx
  become: True


- name: Configure the Tower system user's home directory.
  file: path=/var/lib/awx state=directory owner=awx group=awx mode=0755
  become: True

- name: Configure the Tower system user's .ssh directory.
  file: path=/var/lib/awx/.ssh state=directory owner=awx group=awx mode=0700
  become: True

- name: Configure the Tower projects directory.
  file: path=/var/lib/awx/projects state=directory owner=awx group=awx mode=0750
  become: True

- name: Configure the Tower job output directory.
  file: path=/var/lib/awx/job_status state=directory owner=awx group=awx mode=0750
  become: True

- name: Configure the Tower static directory.
  file: path=/var/lib/awx/public/static state=directory owner=root group=awx mode=0755 recurse=yes
  become: True

- name: Add Towers `conf.d` directory.
  file: path=/etc/tower/conf.d state=directory owner=root group=awx mode=0750
  become: True

- name: configure tower log directory
  file: path=/var/log/tower state=directory owner=awx group=awx mode=0750
  become: True

- name: Update awx_supervisord logrotate config file
  copy:
    src: logrotate_awx_supervisord
    dest: '/etc/logrotate.d/awx_supervisord'
    owner: root
    group: root
    mode: '0644'
  become: True

- name: Update hourly cron logrotate invocation
  copy:
    src: logrotate_cron.hourly
    dest: '/etc/cron.hourly/logrotate'
    owner: root
    group: root
    mode: '0744'
  become: True

# Update service configuration information for the ansible-tower-service script
- name: Update ansible-tower-service configuration
  template:
    src: ansible-tower.sysconfig.j2
    dest: '/etc/sysconfig/ansible-tower'
    owner: root
    group: root
    mode: '0644'
  become: True

# When running with an external database, we need to remove 'postgresql' from
# the list of tower managed services.
- name: Update ansible-tower systemd configuration
  template:
    src: ansible-tower.service.j2
    dest: '/lib/systemd/system/ansible-tower.service'
    owner: root
    group: root
    mode: '0644'
  become: True

- name: Update dependent service configuration
  file:
    path: "/etc/systemd/system/{{ item }}.service.d"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "nginx"
    - "supervisord"
    - "{{ awx_install_redis_init_name }}"
    - "{{ awx_install_pg_init_name | default(omit) }}"
  become: True

- name: Update dependent service configuration
  copy:
    src: "{{ lookup('first_found', override) }}"
    dest: "/etc/systemd/system/{{ item }}.service.d/override.conf"
    mode: 0644
    owner: root
    group: root
  vars:
    override:
      - "files/override-{{ item }}.conf"
      - "files/override.conf"
  loop:
    - "nginx"
    - "supervisord"
    - "{{ awx_install_redis_init_name }}"
    - "{{ awx_install_pg_init_name | default(omit) }}"
  become: True

- name: Reload systemd configuration
  command: systemctl daemon-reload
  become: True

- name: Enable the ansible-tower service
  service:
    name: ansible-tower
    enabled: true
  become: True

- name: Check if this is a fresh installation
  stat:
    path: /var/lib/awx/.tower_version
  register: previous_install_status
  become: True

- name: Configure the Rsyslog socket directory.
  file: path=/var/run/awx-rsyslog state=directory owner=awx group=awx mode=0750
  become: True

- name: Create tmpfiles.d entry for rsyslog socket directory
  template:
    src: rsyslog_tmpd.conf
    dest: /etc/tmpfiles.d/rsyslog.conf
    force: yes
    mode: '0640'
    owner: root
    group: root
  become: True


- name: Collect static files for Tower.
  shell: umask 022 && awx-manage collectstatic --noinput --clear -v0
  become_user: root
  become: True

