- name: install awx-from-source 
  action: template src=dumpall.j2 dest=/tmp/ansible_dump.all

- name: run awx setup install
  ansible.builtin.command: /var/awx/venv/bin/python setup.py install
  become: yes
  args:
    chdir:  /opt/awx

- name: django-debug-toolbar 
  ansible.builtin.command: /var/awx/venv/bin/pip install django-debug-toolbar
  become: yes
  args:
    chdir:  /opt/awx

- name: django-rest-swagger
  ansible.builtin.command: /var/awx/venv/bin/pip install django-rest-swagger
  become: yes
  args:
    chdir:  /opt/awx

- name: Creates tower
  file:
    path: /etc/tower/conf.d
    state: directory
    owner: cloud-user
    group: cloud-user
    mode: 0770
    recurse: yes

- name: create awx settings
  ansible.builtin.template:
    src: templates/settings.py.j2
    dest: /etc/tower/settings.py
    owner: cloud-user
    group: cloud-user
    mode: '0600'
  become: True

- name: create awx secret
  ansible.builtin.template:
    src: templates/SECRET_KEY.j2
    dest: /etc/tower/SECRET_KEY
    owner: cloud-user
    group: cloud-user
    mode: '0600'
  become: True

- name: create awx postgres
  ansible.builtin.template:
    src: templates/postgres.py.j2
    dest: /etc/tower/conf.d/postgres.py
    owner: cloud-user
    group: cloud-user
    mode: '0600'
  become: True
