- name: Prepare server
  import_tasks: prepare-server.yml 

- name: install postgress
 import_tasks: install-postgres.yml 

- name: install redis
  import_tasks: install-redis.yml 

- name: install awx from source
  import_tasks: nginx.yml

  #- name: setup awx services
  # import_tasks: setup-awx-services.yml

