- name: Enable EPEL Repository on CentOS 8
  dnf:
    name: epel-release
    state: latest
  become: True
  when: ansible_facts['os_family'] == 'RedHat'

- name: depend | Ensure dependencies are installed.
  dnf:
    pkg: [
                'jq',
                'redis',
                'git',
                'python3-virtualenv',
                'gcc-c++',
                'nodejs',
                'device-mapper-persistent-data',
                'lvm2',
                'bzip2',
                'python3-pip',
                'ansible',
                'gcc',
                'openldap-devel'

        ]
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install add  packages
  yum:
    name:
      - xmlsec1-devel
      - libtool-ltdl-devel
      - mlocate
      - libpq-devel

    state: latest
    enablerepo: "powertools"
  become: True
  when: ansible_facts['os_family'] == 'RedHat'

- name: Add the group 'awx' with a specific gid and
  ansible.builtin.group:
    name: awx
    state: present
    gid: 1666
  become: True

- name: Add the user 'awx' with a specific uid and a primary group of 'awx'
  ansible.builtin.user:
    name: awx
    comment: awx service accout
    uid: 1666
    group: awx
  become: true 

- name: Create log dir
  file:
    path: /var/log/tower
    owner: awx
    group: awx
    state: directory
    mode: "u=rwx,g=rwx,o=r"
  become: yes

- name: Create log dir
  file:
    path: /var/lib/awx
    owner: awx
    group: awx
    state: directory
    mode: "u=rwx,g=rwx,o=r"
  become: yes

- name: Git checkout awx
  ansible.builtin.git:
    repo: 'https://github.com/ansible/awx.git'
    dest: /tmp/awx
    version: "{{ awx_image_version }}"
  become: True
  become_user: awx

- name: Recursively change ownership of the directory
  ansible.builtin.file:
    path: /tmp/awx
    state: directory
    recurse: yes
    owner: awx
    group: awx
  become: True

- name:  create venv
  ansible.builtin.pip:
    requirements: /opt/awx/requirements/requirements.txt
    virtualenv: /var/awx/venv
    virtualenv_command: /usr/bin/python3 -m venv
  become: True
